name = "future-au-site"
main = "dist/_worker.js/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "futureaupodcast.com.au/*", zone_name = "futureaupodcast.com.au" },
  { pattern = "www.futureaupodcast.com.au/*", zone_name = "futureaupodcast.com.au" }
]

[assets]
directory = "./dist"

[vars]
CONTACT_EMAIL = "hello@futureaupodcast.com.au"

[[kv_namespaces]]
binding = "SUBSCRIBERS_KV"
id = "679ce65897de4813927e8719a0972478"

# Set RESEND_API_KEY as a secret:
# wrangler secret put RESEND_API_KEY
